name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify
